_format_version: "2.1"
_transform: true


services:
  - name: quote-service
    url: http://quotes:8080
    routes:
      - name: quote-service-routes
        paths:
          - /quotes
        strip_path: true
  - name: user-service
    url: http://nestjs_api:9000
    routes:
      - name: user-service-auth-routes
        paths:
          - /api/v1/auth/login
          - /api/v1/auth/register
          - /api/v1/auth/account/confirm
        strip_path: false
  - name: order-service
      url: http://nestjs_api:9001
      routes:
        - name: order-service-auth-routes
          paths:
            - /
            - /api/v1/auth/register
          strip_path: true


